=== dreamdata-io/tap-agilecrm/tap_agilecrm/schemas/deal_schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "apply_discount",
    "archived",
    "colorName",
    "contact_ids",
    "contacts",
    "created_time",
    "custom_data",
    "deal_source_id",
    "discount_amt",
    "discount_type",
    "discount_value",
    "entity_type",
    "id",
    "isCurrencyUpdateRequired",
    "lost_reason_id",
    "milestone",
    "milestone_changed_time",
    "name",
    "note_created_time",
    "note_ids",
    "notes",
    "pipeline_id",
    "probability",
    "products",
    "tags",
    "tagsWithTime",
    "total_deal_value",
    "updated_time"
  ],
  "properties": {
    "apply_discount": {
      "$id": "#/properties/apply_discount",
      "type": "boolean",
      "title": "The Apply_discount Schema",
      "default": false,
      "examples": [
        false
      ]
    },
    "archived": {
      "$id": "#/properties/archived",
      "type": "boolean",
      "title": "The Archived Schema",
      "default": false,
      "examples": [
        false
      ]
    },
    "close_date": {
      "$id": "#/properties/close_date",
      "type": "integer",
      "title": "The Close_date Schema",
      "default": 0,
      "examples": [
        1234567890
      ]
    },
    "colorName": {
      "$id": "#/properties/colorName",
      "type": "string",
      "title": "The Colorname Schema",
      "default": "",
      "examples": [
        "WHITE"
      ]
    },
    "contact_ids": {
      "$id": "#/properties/contact_ids",
      "type": "array",
      "title": "The Contact_ids Schema",
      "items": {
        "$id": "#/properties/contact_ids/items",
        "type": "string",
        "title": "The Items Schema",
        "default": "",
        "examples": [
          "1234567890123456"
        ]
      }
    },
    "contacts": {
      "$id": "#/properties/contacts",
      "type": "array",
      "title": "The Contacts Schema",
      "items": {
        "$id": "#/properties/contacts/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "id",
          "properties"
        ],
        "properties": {
          "id": {
            "$id": "#/properties/contacts/items/properties/id",
            "type": "integer",
            "title": "The Id Schema",
            "default": 0,
            "examples": [
              1234567890123456
            ]
          },
          "properties": {
            "$id": "#/properties/contacts/items/properties/properties",
            "type": "array",
            "title": "The Properties Schema",
            "items": {
              "$id": "#/properties/contacts/items/properties/properties/items",
              "type": "object",
              "title": "The Items Schema",
              "required": [
                "name",
                "type",
                "value"
              ],
              "properties": {
                "name": {
                  "$id": "#/properties/contacts/items/properties/properties/items/properties/name",
                  "type": "string",
                  "title": "The Name Schema",
                  "default": "",
                  "examples": [
                    "name"
                  ]
                },
                "type": {
                  "$id": "#/properties/contacts/items/properties/properties/items/properties/type",
                  "type": "string",
                  "title": "The Type Schema",
                  "default": "",
                  "examples": [
                    "SYSTEM"
                  ]
                },
                "value": {
                  "$id": "#/properties/contacts/items/properties/properties/items/properties/value",
                  "type": "string",
                  "title": "The Value Schema",
                  "default": "",
                  "examples": [
                    "<NAME>"
                  ]
                }
              }
            }
          },
          "type": {
            "$id": "#/properties/contacts/items/properties/type",
            "type": "string",
            "title": "The Type Schema",
            "default": "",
            "examples": [
              "COMPANY"
            ]
          }
        }
      }
    },
    "created_time": {
      "$id": "#/properties/created_time",
      "type": "integer",
      "title": "The Created_time Schema",
      "default": 0,
      "examples": [
        1234567890
      ]
    },
    "currency_conversion_value": {
      "$id": "#/properties/currency_conversion_value",
      "type": "number",
      "title": "The Currency_conversion_value Schema",
      "default": 0,
      "examples": [
        1
      ]
    },
    "custom_data": {
      "$id": "#/properties/custom_data",
      "type": "array",
      "title": "The Custom_data Schema",
      "items": {
        "$id": "#/properties/custom_data/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "name",
          "value"
        ],
        "properties": {
          "name": {
            "$id": "#/properties/custom_data/items/properties/name",
            "type": "string",
            "title": "The Name Schema",
            "default": "",
            "examples": [
              "<NAME>"
            ]
          },
          "value": {
            "$id": "#/properties/custom_data/items/properties/value",
            "type": "string",
            "title": "The Value Schema",
            "default": "",
            "examples": [
              "<VALUE>"
            ]
          }
        }
      }
    },
    "deal_source_id": {
      "$id": "#/properties/deal_source_id",
      "type": "integer",
      "title": "The Deal_source_id Schema",
      "default": 0,
      "examples": [
        1234567890123456
      ]
    },
    "description": {
      "$id": "#/properties/description",
      "type": "string",
      "title": "The Description Schema",
      "default": "",
      "examples": [
        ""
      ]
    },
    "discount_amt": {
      "$id": "#/properties/discount_amt",
      "type": "number",
      "title": "The Discount_amt Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "discount_type": {
      "$id": "#/properties/discount_type",
      "type": "string",
      "title": "The Discount_type Schema",
      "default": "",
      "examples": [
        "<VALUE>"
      ]
    },
    "discount_value": {
      "$id": "#/properties/discount_value",
      "type": "number",
      "title": "The Discount_value Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "entity_type": {
      "$id": "#/properties/entity_type",
      "type": "string",
      "title": "The Entity_type Schema",
      "default": "",
      "examples": [
        "deal"
      ]
    },
    "expected_value": {
      "$id": "#/properties/expected_value",
      "type": "number",
      "title": "The Expected_value Schema",
      "default": 0,
      "examples": [
        1
      ]
    },
    "id": {
      "$id": "#/properties/id",
      "type": "integer",
      "title": "The Id Schema",
      "default": 0,
      "examples": [
        1234567890123456
      ]
    },
    "isCurrencyUpdateRequired": {
      "$id": "#/properties/isCurrencyUpdateRequired",
      "type": "boolean",
      "title": "The Iscurrencyupdaterequired Schema",
      "default": false,
      "examples": [
        true
      ]
    },
    "lost_reason_id": {
      "$id": "#/properties/lost_reason_id",
      "type": "integer",
      "title": "The Lost_reason_id Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "milestone": {
      "$id": "#/properties/milestone",
      "type": "string",
      "title": "The Milestone Schema",
      "default": "",
      "examples": [
        "<MILESTONE>"
      ]
    },
    "milestone_changed_time": {
      "$id": "#/properties/milestone_changed_time",
      "type": "integer",
      "title": "The Milestone_changed_time Schema",
      "default": 0,
      "examples": [
        1234567890
      ]
    },
    "name": {
      "$id": "#/properties/name",
      "type": "string",
      "title": "The Name Schema",
      "default": "",
      "examples": [
        "<NAME>"
      ]
    },
    "note_created_time": {
      "$id": "#/properties/note_created_time",
      "type": "integer",
      "title": "The Note_created_time Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "note_ids": {
      "$id": "#/properties/note_ids",
      "type": "array",
      "title": "The Note_ids Schema"
    },
    "notes": {
      "$id": "#/properties/notes",
      "type": "array",
      "title": "The Notes Schema"
    },
    "pipeline_id": {
      "$id": "#/properties/pipeline_id",
      "type": "integer",
      "title": "The Pipeline_id Schema",
      "default": 0,
      "examples": [
        1234567890123456
      ]
    },
    "probability": {
      "$id": "#/properties/probability",
      "type": "integer",
      "title": "The Probability Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "products": {
      "$id": "#/properties/products",
      "type": "array",
      "title": "The Products Schema"
    },
    "tags": {
      "$id": "#/properties/tags",
      "type": "array",
      "title": "The Tags Schema",
      "items": {
        "$id": "#/properties/tags/items",
        "type": "string",
        "title": "The Items Schema",
        "default": "",
        "examples": [
          "<tag1>",
          "<tag2>"
        ]
      }
    },
    "tagsWithTime": {
      "$id": "#/properties/tagsWithTime",
      "type": "array",
      "title": "The Tagswithtime Schema",
      "items": {
        "$id": "#/properties/tagsWithTime/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "tag",
          "createdTime",
          "availableCount",
          "entity_type"
        ],
        "properties": {
          "tag": {
            "$id": "#/properties/tagsWithTime/items/properties/tag",
            "type": "string",
            "title": "The Tag Schema",
            "default": "",
            "examples": [
              "<tag1>"
            ]
          },
          "createdTime": {
            "$id": "#/properties/tagsWithTime/items/properties/createdTime",
            "type": "integer",
            "title": "The Createdtime Schema",
            "default": 0,
            "examples": [
              1234567890
            ]
          },
          "availableCount": {
            "$id": "#/properties/tagsWithTime/items/properties/availableCount",
            "type": "integer",
            "title": "The Availablecount Schema",
            "default": 0,
            "examples": [
              0
            ]
          },
          "entity_type": {
            "$id": "#/properties/tagsWithTime/items/properties/entity_type",
            "type": "string",
            "title": "The Entity_type Schema",
            "default": "",
            "examples": [
              "tag"
            ]
          }
        }
      }
    },
    "total_deal_value": {
      "$id": "#/properties/total_deal_value",
      "type": "number",
      "title": "The Total_deal_value Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "updated_time": {
      "$id": "#/properties/updated_time",
      "type": "integer",
      "title": "The Updated_time Schema",
      "default": 0,
      "examples": [
        1234567890
      ]
    }
  }
}

=== dreamdata-io/tap-agilecrm/schemas/deal_payload.json
{
  "apply_discount": false,
  "archived": false,
  "close_date": 1234567890,
  "colorName": "WHITE",
  "contact_ids": [
    "1234567890123456"
  ],
  "contacts": [
    {
      "id": 1234567890123456,
      "properties": [
        {
          "name": "name",
          "type": "SYSTEM",
          "value": "<NAME>"
        }
      ],
      "type": "COMPANY"
    },
    {
      "id": 1234567890123456,
      "properties": [
        {
          "name": "first_name",
          "type": "SYSTEM",
          "value": "<VALUE>"
        },
        {
          "name": "last_name",
          "type": "SYSTEM",
          "value": "<VALUE>"
        }
      ],
      "type": "PERSON"
    }
  ],
  "created_time": 1234567890,
  "currency_conversion_value": 1.0,
  "custom_data": [
    {
      "name": "<NAME>",
      "value": "<VALUE>"
    }
  ],
  "deal_source_id": 1234567890123456,
  "description": "",
  "discount_amt": 0.0,
  "discount_type": "<VALUE>",
  "discount_value": 0.0,
  "entity_type": "deal",
  "expected_value": 1.0,
  "id": 1234567890123456,
  "isCurrencyUpdateRequired": true,
  "lost_reason_id": 0,
  "milestone": "<MILESTONE>",
  "milestone_changed_time": 1234567890,
  "name": "<NAME>",
  "note_created_time": 0,
  "note_ids": [],
  "notes": [],
  "pipeline_id": 1234567890123456,
  "probability": 0,
  "products": [],
  "tags": [],
  "tagsWithTime": [],
  "total_deal_value": 0.0,
  "updated_time": 1234567890
}
