=== dreamdata-io/tap-agilecrm/schemas/company_entity_schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "browserId",
    "campaignStatus",
    "concurrent_save_allowed",
    "created_time",
    "emailBounceStatus",
    "entity_type",
    "formId",
    "id",
    "is_client_import",
    "is_duplicate_existed",
    "is_duplicate_verification_failed",
    "is_lead_converted",
    "klout_score",
    "last_called",
    "last_campaign_emaild",
    "last_contacted",
    "last_emailed",
    "lead_converted_time",
    "lead_score",
    "lead_source_id",
    "lead_status_id",
    "properties",
    "restored_time",
    "star_value",
    "tags",
    "tagsWithTime",
    "trashed_time",
    "type",
    "unsubscribeStatus",
    "updated_time",
    "viewed",
    "viewed_time"
  ],
  "properties": {
    "browserId": {
      "$id": "#/properties/browserId",
      "type": "array",
      "title": "The Browserid Schema"
    },
    "campaignStatus": {
      "$id": "#/properties/campaignStatus",
      "type": "array",
      "title": "The Campaignstatus Schema"
    },
    "concurrent_save_allowed": {
      "$id": "#/properties/concurrent_save_allowed",
      "type": "boolean",
      "title": "The Concurrent_save_allowed Schema",
      "default": false,
      "examples": [
        true
      ]
    },
    "created_time": {
      "$id": "#/properties/created_time",
      "type": "integer",
      "title": "The Created_time Schema",
      "default": 0,
      "examples": [
        1234567890
      ]
    },
    "emailBounceStatus": {
      "$id": "#/properties/emailBounceStatus",
      "type": "array",
      "title": "The Emailbouncestatus Schema"
    },
    "entity_type": {
      "$id": "#/properties/entity_type",
      "type": "string",
      "title": "The Entity_type Schema",
      "default": "",
      "examples": [
        "company_entity"
      ],
      "pattern": "^(.*)$"
    },
    "formId": {
      "$id": "#/properties/formId",
      "type": "integer",
      "title": "The Formid Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "id": {
      "$id": "#/properties/id",
      "type": "integer",
      "title": "The Id Schema",
      "default": 0,
      "examples": [
        1234567890123456
      ]
    },
    "is_client_import": {
      "$id": "#/properties/is_client_import",
      "type": "boolean",
      "title": "The Is_client_import Schema",
      "default": false,
      "examples": [
        false
      ]
    },
    "is_duplicate_existed": {
      "$id": "#/properties/is_duplicate_existed",
      "type": "boolean",
      "title": "The Is_duplicate_existed Schema",
      "default": false,
      "examples": [
        false
      ]
    },
    "is_duplicate_verification_failed": {
      "$id": "#/properties/is_duplicate_verification_failed",
      "type": "boolean",
      "title": "The Is_duplicate_verification_failed Schema",
      "default": false,
      "examples": [
        false
      ]
    },
    "is_lead_converted": {
      "$id": "#/properties/is_lead_converted",
      "type": "boolean",
      "title": "The Is_lead_converted Schema",
      "default": false,
      "examples": [
        false
      ]
    },
    "klout_score": {
      "$id": "#/properties/klout_score",
      "type": "string",
      "title": "The Klout_score Schema",
      "default": "",
      "examples": [
        ""
      ],
      "pattern": "^(.*)$"
    },
    "last_called": {
      "$id": "#/properties/last_called",
      "type": "integer",
      "title": "The Last_called Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "last_campaign_emaild": {
      "$id": "#/properties/last_campaign_emaild",
      "type": "integer",
      "title": "The Last_campaign_emaild Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "last_contacted": {
      "$id": "#/properties/last_contacted",
      "type": "integer",
      "title": "The Last_contacted Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "last_emailed": {
      "$id": "#/properties/last_emailed",
      "type": "integer",
      "title": "The Last_emailed Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "lead_converted_time": {
      "$id": "#/properties/lead_converted_time",
      "type": "integer",
      "title": "The Lead_converted_time Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "lead_score": {
      "$id": "#/properties/lead_score",
      "type": "integer",
      "title": "The Lead_score Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "lead_source_id": {
      "$id": "#/properties/lead_source_id",
      "type": "integer",
      "title": "The Lead_source_id Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "lead_status_id": {
      "$id": "#/properties/lead_status_id",
      "type": "integer",
      "title": "The Lead_status_id Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "owner": {
      "$id": "#/properties/owner",
      "type": "object",
      "title": "The Owner Schema",
      "required": [
        "calendarURL",
        "calendar_url",
        "domain",
        "email",
        "id",
        "name",
        "phone",
        "pic",
        "schedule_id"
      ],
      "properties": {
        "calendarURL": {
          "$id": "#/properties/owner/properties/calendarURL",
          "type": "string",
          "title": "The Calendarurl Schema",
          "default": "",
          "examples": [
            "<URL>"
          ],
          "pattern": "^(.*)$"
        },
        "calendar_url": {
          "$id": "#/properties/owner/properties/calendar_url",
          "type": "string",
          "title": "The Calendar_url Schema",
          "default": "",
          "examples": [
            "<URL>"
          ],
          "pattern": "^(.*)$"
        },
        "domain": {
          "$id": "#/properties/owner/properties/domain",
          "type": "string",
          "title": "The Domain Schema",
          "default": "",
          "examples": [
            "<DOMAIN>"
          ],
          "pattern": "^(.*)$"
        },
        "email": {
          "$id": "#/properties/owner/properties/email",
          "type": "string",
          "title": "The Email Schema",
          "default": "",
          "examples": [
            "<EMAIL_EXAMPLE>"
          ],
          "pattern": "^(.*)$"
        },
        "id": {
          "$id": "#/properties/owner/properties/id",
          "type": "integer",
          "title": "The Id Schema",
          "default": 0,
          "examples": [
            1234567890123456
          ]
        },
        "name": {
          "$id": "#/properties/owner/properties/name",
          "type": "string",
          "title": "The Name Schema",
          "default": "",
          "examples": [
            "<OWNER_NAME>"
          ],
          "pattern": "^(.*)$"
        },
        "phone": {
          "$id": "#/properties/owner/properties/phone",
          "type": "string",
          "title": "The Phone Schema",
          "default": "",
          "examples": [
            "<OWNER_PHONE>"
          ],
          "pattern": "^(.*)$"
        },
        "pic": {
          "$id": "#/properties/owner/properties/pic",
          "type": "string",
          "title": "The Pic Schema",
          "default": "",
          "examples": [
            "<URI>"
          ],
          "pattern": "^(.*)$"
        },
        "schedule_id": {
          "$id": "#/properties/owner/properties/schedule_id",
          "type": "string",
          "title": "The Schedule_id Schema",
          "default": "",
          "examples": [
            "<SCHEDULE_ID>"
          ],
          "pattern": "^(.*)$"
        }
      }
    },
    "properties": {
      "$id": "#/properties/properties",
      "type": "array",
      "title": "The Properties Schema",
      "items": {
        "$id": "#/properties/properties/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "name",
          "type",
          "value"
        ],
        "properties": {
          "name": {
            "$id": "#/properties/properties/items/properties/name",
            "type": "string",
            "title": "The Name Schema",
            "default": "",
            "examples": [
              "<name>"
            ],
            "pattern": "^(.*)$"
          },
          "type": {
            "$id": "#/properties/properties/items/properties/type",
            "type": "string",
            "title": "The Type Schema",
            "default": "",
            "examples": [
              "SYSTEM"
            ],
            "pattern": "^(.*)$"
          },
          "subtype": {
            "$id": "#/properties/properties/items/properties/subtype",
            "type": "string",
            "title": "The Subtype Schema",
            "default": "",
            "examples": [
              "<SUBTYPE>"
            ],
            "pattern": "^(.*)$"
          },
          "value": {
            "$id": "#/properties/properties/items/properties/value",
            "type": "string",
            "title": "The Value Schema",
            "default": "",
            "examples": [
              "<VALUE>"
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    },
    "restored_time": {
      "$id": "#/properties/restored_time",
      "type": "integer",
      "title": "The Restored_time Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "star_value": {
      "$id": "#/properties/star_value",
      "type": "integer",
      "title": "The Star_value Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "tags": {
      "$id": "#/properties/tags",
      "type": "array",
      "title": "The Tags Schema",
      "items": {
        "$id": "#/properties/tags/items",
        "type": "string",
        "title": "The Items Schema",
        "default": "",
        "examples": [
          "<tag1>",
          "<tag2>"
        ],
        "pattern": "^(.*)$"
      }
    },
    "tagsWithTime": {
      "$id": "#/properties/tagsWithTime",
      "type": "array",
      "title": "The Tagswithtime Schema",
      "items": {
        "$id": "#/properties/tagsWithTime/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "tag",
          "createdTime",
          "availableCount",
          "entity_type"
        ],
        "properties": {
          "tag": {
            "$id": "#/properties/tagsWithTime/items/properties/tag",
            "type": "string",
            "title": "The Tag Schema",
            "default": "",
            "examples": [
              "<tag1>"
            ],
            "pattern": "^(.*)$"
          },
          "createdTime": {
            "$id": "#/properties/tagsWithTime/items/properties/createdTime",
            "type": "integer",
            "title": "The Createdtime Schema",
            "default": 0,
            "examples": [
              1234567890
            ]
          },
          "availableCount": {
            "$id": "#/properties/tagsWithTime/items/properties/availableCount",
            "type": "integer",
            "title": "The Availablecount Schema",
            "default": 0,
            "examples": [
              0
            ]
          },
          "entity_type": {
            "$id": "#/properties/tagsWithTime/items/properties/entity_type",
            "type": "string",
            "title": "The Entity_type Schema",
            "default": "",
            "examples": [
              "tag"
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    },
    "trashed_time": {
      "$id": "#/properties/trashed_time",
      "type": "integer",
      "title": "The Trashed_time Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "type": {
      "$id": "#/properties/type",
      "type": "string",
      "title": "The Type Schema",
      "default": "",
      "examples": [
        "COMPANY"
      ],
      "pattern": "^(.*)$"
    },
    "unsubscribeStatus": {
      "$id": "#/properties/unsubscribeStatus",
      "type": "array",
      "title": "The Unsubscribestatus Schema"
    },
    "updated_time": {
      "$id": "#/properties/updated_time",
      "type": "integer",
      "title": "The Updated_time Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "viewed": {
      "$id": "#/properties/viewed",
      "type": "object",
      "title": "The Viewed Schema",
      "required": [
        "viewed_time"
      ],
      "properties": {
        "viewed_time": {
          "$id": "#/properties/viewed/properties/viewed_time",
          "type": "integer",
          "title": "The Viewed_time Schema",
          "default": 0,
          "examples": [
            0
          ]
        }
      }
    },
    "viewed_time": {
      "$id": "#/properties/viewed_time",
      "type": "integer",
      "title": "The Viewed_time Schema",
      "default": 0,
      "examples": [
        0
      ]
    }
  }
}

=== dreamdata-io/tap-agilecrm/schemas/company_entity_payload.json
{
  "browserId": [],
  "campaignStatus": [],
  "concurrent_save_allowed": true,
  "created_time": 1234567890,
  "emailBounceStatus": [],
  "entity_type": "company_entity",
  "formId": 0,
  "id": 1234567890123456,
  "is_client_import": false,
  "is_duplicate_existed": false,
  "is_duplicate_verification_failed": false,
  "is_lead_converted": false,
  "klout_score": "",
  "last_called": 0,
  "last_campaign_emaild": 0,
  "last_contacted": 0,
  "last_emailed": 0,
  "lead_converted_time": 0,
  "lead_score": 0,
  "lead_source_id": 0,
  "lead_status_id": 0,
  "owner": {
    "calendarURL": "<URL>",
    "calendar_url": "<URL>",
    "domain": "<DOMAIN>",
    "email": "<EMAIL_EXAMPLE>",
    "id": 1234567890123456,
    "name": "<OWNER_NAME>",
    "phone": "<OWNER_PHONE>",
    "pic": "<URI>",
    "schedule_id": "<SCHEDULE_ID>"
  },
  "properties": [
    {
      "name": "<name>",
      "type": "SYSTEM",
      "subtype": "<SUBTYPE>",
      "value": "<VALUE>"
    },
    {
      "name": "<name>",
      "type": "SYSTEM",
      "value": "<VALUE>"
    }
  ],
  "restored_time": 0,
  "star_value": 0,
  "tags": [
    "<tag1>",
    "<tag2>"
  ],
  "tagsWithTime": [
    {
      "tag": "<tag1>",
      "createdTime": 1234567890,
      "availableCount": 0,
      "entity_type": "tag"
    }
  ],
  "trashed_time": 0,
  "type": "COMPANY",
  "unsubscribeStatus": [],
  "updated_time": 0,
  "viewed": {
    "viewed_time": 0
  },
  "viewed_time": 0
}
